datadir: /local/gainondefor/work/lip6/data/extendedresume
prevdatadir: /local/gainondefor/work/lip6/data/seq2seq
gpudatadir: /local/gainondefor/work/data/extendedresume
modeldir: /data/gainondefor/extendedresume/
rep:
  ft:
    total: reps/ft_emb/30_latest_clus_cie_per_skills
  sk:
    total: reps/skills/30_clus_latest_ppl_as_bin_skills

